//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThiCK_62130808.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ThiCK_62130808Entities : DbContext
    {
        public ThiCK_62130808Entities()
            : base("name=ThiCK_62130808Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LOAITAISAN> LOAITAISANs { get; set; }
        public virtual DbSet<TAISAN> TAISANs { get; set; }
    
        public virtual int TaiSan_TimKiem(string tenTS, Nullable<int> donGiaFrom, Nullable<int> donGiaTo)
        {
            var tenTSParameter = tenTS != null ?
                new ObjectParameter("TenTS", tenTS) :
                new ObjectParameter("TenTS", typeof(string));
    
            var donGiaFromParameter = donGiaFrom.HasValue ?
                new ObjectParameter("DonGiaFrom", donGiaFrom) :
                new ObjectParameter("DonGiaFrom", typeof(int));
    
            var donGiaToParameter = donGiaTo.HasValue ?
                new ObjectParameter("DonGiaTo", donGiaTo) :
                new ObjectParameter("DonGiaTo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TaiSan_TimKiem", tenTSParameter, donGiaFromParameter, donGiaToParameter);
        }
    }
}
