//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KT0720_62133366.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class KT0720_62133366Entities1 : DbContext
    {
        public KT0720_62133366Entities1()
            : base("name=KT0720_62133366Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Lop> Lops { get; set; }
        public virtual DbSet<SinhVien> SinhViens { get; set; }
    
        public virtual ObjectResult<TimKiemNhanVien_Result> TimKiemNhanVien(string maSV, string tenSV)
        {
            var maSVParameter = maSV != null ?
                new ObjectParameter("MaSV", maSV) :
                new ObjectParameter("MaSV", typeof(string));
    
            var tenSVParameter = tenSV != null ?
                new ObjectParameter("TenSV", tenSV) :
                new ObjectParameter("TenSV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TimKiemNhanVien_Result>("TimKiemNhanVien", maSVParameter, tenSVParameter);
        }
    
        public virtual ObjectResult<TimKiemSinhVien_Result> TimKiemSinhVien(string maSV, string tenSV)
        {
            var maSVParameter = maSV != null ?
                new ObjectParameter("MaSV", maSV) :
                new ObjectParameter("MaSV", typeof(string));
    
            var tenSVParameter = tenSV != null ?
                new ObjectParameter("TenSV", tenSV) :
                new ObjectParameter("TenSV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TimKiemSinhVien_Result>("TimKiemSinhVien", maSVParameter, tenSVParameter);
        }
    
        public virtual int TimKiemSV(string maSV, string hoTen)
        {
            var maSVParameter = maSV != null ?
                new ObjectParameter("MaSV", maSV) :
                new ObjectParameter("MaSV", typeof(string));
    
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TimKiemSV", maSVParameter, hoTenParameter);
        }
    }
}
